version: '2'
services:
  mongo:
    image: mongodb:latest
    hostname: "mongodb"
    environment:
      HAB_MONGODB: "[mongod.net]\nbind_ip = '0.0.0.0'\n[mongod.security]\ncluster_auth_mode = ''"
  national-parks:
    image: nationalparks:latest
    ports:
      - "8080:8080"
    links:
      - mongo:mongodb
    command: --peer mongodb --bind database:mongodb.default

